export const categoryOptions = [
  { value: "", label: "Select Category" },
  { value: "programming", label: "Programming and Coding" },
  { value: "web-development", label: "Web Development" },
  { value: "app-development", label: "Mobile App Development" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "data-science", label: "Data Science and Analytics" },
  { value: "hardware-gadgets", label: "Hardware and Gadgets" },
  { value: "dev-tools", label: "Software Development Tools" },
  { value: "iot", label: "Internet of Things (IoT)" },
  { value: "artificial-intelligence", label: "Artificial Intelligence (AI)" },
  { value: "industry-news", label: "Tech Industry News" },
  { value: "tech-tips", label: "Tech Tips and Tricks" },
  { value: "game-development", label: "Game Development" },
  { value: "blockchain-crypto", label: "Blockchain and Cryptocurrency" },
  { value: "tech-ethics-privacy", label: "Tech Ethics and Privacy" },
  { value: "future-trends", label: "Future Technology Trends" },
];
